### ISSUE TITLE
"TypeError: FPDF._putresources() takes 1 positional argument but 2 were given" from AlphaFPDF

### ISSUE THREAD

**Issue by marcstober** [digidigital/Extensions-and-Scripts-for-pyFPDF-fpdf2#1]
When I try to use **AlphaFPDF**, I get the following error:

> TypeError: FPDF._putresources() takes 1 positional argument but 2 were given

This is coming from the line of code referenced below. The line of code has:
`super()._enddoc(self)`

If I change it to the following (take out `self`), it works:
`super()._enddoc()`

I don't understand how it would have worked with `self`. Maybe it runs correctly in a different version of Python (I'm using 3.10.5)?

https://github.com/digidigital/Extensions-and-Scripts-for-pyFPDF-fpdf2/blob/2c35554f5234080e35f617ec4d43661c514c8f2e/alpha/AlphaFPDF.py#L35

**Comment by digidigital** [comment]
Hi Marc, I tested the scripts with Python 3.8.10 and fpdf 2.7.5 and they were working fine (I hope I did not change the code after testing). Since then a lot has happened and transparency is now a feature of fdpf2 anyway -> [LINK](https://py-pdf.github.io/fpdf2/Transparency.html)

**Comment by marcstober** [comment]
Thank you.
